Update behaviour header
fakob/plug-and-play pull request #101
Opened 2022-05-18 19:22 UTC by fakob

This PR should visualise the update behaviour for each node in a simple way. Even though this is not perfect, I think it is a good first step.

A small element on the top of every node
* shows the update behaviour
  * if update is selected -> nothing is shown (as this is the default setting)
  * if update is not selected -> a square is shown (sort of like a stop sign)
  * if interval is selected -> the interval frequency is shown
* allows to update now
  * when hovering over a node -> a circle button is shown, clicking it does the same as "update now"

<img width="403" alt="Screen Shot 2022-05-18 at 21 11 39" src="https://user-images.githubusercontent.com/4619772/169138625-455474b2-f545-4e51-97ba-0f5a15817660.png">

2022-05-19 19:57 UTC, magnificus requested changes
Cool stuff looking forward to try it, however there is one thing that I think would be better changed, left comments.

2022-05-19 19:57 UTC, magnificus commented on src/classes/NodeClass.ts
> +  protected init(): void {}
I would highly recommend making the init function private and only call it in PPNode and keep the getUpdateBehaviour in the child classes. This way we can keep the children "pure" and free of side effects.

2022-05-19 19:57 UTC, magnificus commented on src/nodes/api/get.tsx
> +  protected init(): void {
following up on above comment, I would keep this one as it is and only call the init in the top parent class, to avoid sullying the children in side effects.

2022-05-20 19:20 UTC, fakob commented on src/classes/NodeClass.ts
> +  protected init(): void {}
I had changed it at the beginning as I did not fully understand it and had problems making it work. Seems that I have now figured it out and made an update. Please check

2022-05-25 19:20 UTC, magnificus approved these changes

2022-05-26 11:00 UTC, merged