Create widget from socket
fakob/plug-and-play pull request #108
Opened 2022-06-02 19:26 UTC by fakob

I added
* the ability to right click on the socket name
  * for inputs, allow connecting widget nodes
  * for outputs allow to connect a label node 
* added a delete socket action for none default sockets
  * I have updated all nodes to use `getDefaultIO` for socket creation

https://user-images.githubusercontent.com/4619772/171721168-19866101-9ec2-4439-8894-c0a2308f10dd.mp4
<img width="366" alt="Screenshot_2022-06-01_at_22 44 44" src="https://user-images.githubusercontent.com/4619772/171721191-5a02dc85-5831-4666-a201-b3113165eef2.png">

2022-06-09 17:56 UTC, magnificus requested changes
if possible please change the switching on types, otherwise looks good

2022-06-09 17:56 UTC, magnificus commented on src/App.tsx
> +        case target.parent instanceof PPSocket && target instanceof PIXI.Text:
I know this is old but switching on instanceof is considered ugly, this is when polymorphism pattern would dictate that this is defined inside the classes themselves (so that i dont see those child classes from the outside)

2022-06-09 17:56 UTC, magnificus commented on src/classes/GraphClass.ts
> +    switch (socketDataType) {
instead of this, add function inside datatype that is overriding, dont switch on type here outside. Similar to the one above.

2022-06-09 17:56 UTC, magnificus commented on src/nodes/logViewer.tsx
> +  public getName(): string {
good

2022-06-09 18:49 UTC, fakob commented on src/classes/GraphClass.ts
> +    switch (socketDataType) {
Good point. I have now submitted a fix for this and also consolidated the addLabelWidget function into this one.

2022-06-09 21:09 UTC, magnificus commented on src/App.tsx
> +        case target.parent instanceof PPSocket && target instanceof PIXI.Text:
It would involve making a shared interface (a class called Clickable for example) with a function clickBehaviour (or a better name) that PPSocket, PPNode, and Viewport would extend, then they override those functions, we can look at it, not as important as the one below, feel free to merge before we fix this

2022-06-12 10:02 UTC, magnificus approved these changes

2022-06-12 11:12 UTC, merged