Switching column and row order and execution visualisation
fakob/plug-and-play pull request #120
Opened 2022-07-13 20:06 UTC by fakob

* Added support for switching column and row order for multiply node
* Added support for turning of execution visualisation

2022-07-19 19:32 UTC, magnificus requested changes

2022-07-19 19:32 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +        if (changeDrawingOrder) {
instead of changing them and changing them back (stateful operation), just declare new variables:

x = changeDrawingOrder ? j : i;

etc.

2022-07-19 19:32 UTC, magnificus commented on src/App.tsx
> +  const [showExecutionVisualisation, setShowExecutionVisualisation] =
This is OK but we are starting to suffer some performance concerns from this massive top component, can this state be moved down? Does anything up here use this?

2022-07-20 19:21 UTC, fakob commented on src/nodes/draw/draw.tsx
> +        if (changeDrawingOrder) {
Ah of course. Good idea.

2022-07-20 19:23 UTC, fakob commented
I have also added storing showExecutionVisualisation boolean in the graph.

2022-07-21 17:03 UTC, magnificus approved these changes

2022-07-21 19:21 UTC, merged