Drag link on node
fakob/plug-and-play pull request #147
Opened 2022-09-22 17:45 UTC by fakob

This feature allows you to drag connections from inputs or outputs directly onto another node.  In addition I have also added both preferred input and output socket index. The logic is:
* if node has a preferred socket index without connection > use it
* if node has a socket with the same type without connection > use it
* if node has a AnyType socket without connection > use it
* if node has a socket without connection > use it
* if all sockets have connections, connect to preferred socket, else connect to first socket

I have gone through some of the nodes and added preferred sockets were I thought it fits.

2022-09-24 08:44 UTC, magnificus requested changes

2022-09-24 08:44 UTC, magnificus commented on src/classes/NodeClass.ts
> +  getPreferredInputSocketIndex(): number | undefined {
Can we instead of using indices here use string for name? I have tried to remove all references to indices in the nodes in order to make adding/removing inputs/outputs not cause issues.

2022-09-24 08:44 UTC, magnificus commented on src/nodes/table.tsx
> +  getPreferredInputSocketIndex(): number {
1 here means nothing to me so a string will be much more clear I think

2022-09-24 08:44 UTC, magnificus commented on src/utils/utils.ts
> +  if (socketArray.length > 0) {
no need to check for size 0, you either find it or you don't, no matter the size

2022-09-24 08:44 UTC, magnificus commented on src/utils/utils.ts
> +    // if the node has a preferredInputSocket (with no connection), use it
This function can be made a lot shorter, I would do something like this:

targetArray = isOutput ? node.getPreferredOutputSocket : node.getPreferredInputSocket();
mainTarget= targetArray.find("that node existsand has no link to it")
anyTarget= targetArray.find("anytype that has no link to it")
lastChoice = targetArray.find("any available socket")
return mainTarget || anyTarget || lastChoice.

2022-09-24 08:46 UTC, magnificus commented on src/classes/NodeClass.ts
> +  getPreferredInputSocketIndex(): number | undefined {
Also, lets not make it possible to return undefined, lets just make the default some silly (but explicit) string like
"MyPreferredInputSocket"

2022-09-24 08:47 UTC, magnificus commented on src/utils/utils.ts
> +    // if the node has a preferredInputSocket (with no connection), use it
bonus, making this a oneliner will save performance as the last two don't have to be evaluated if something is found in first (though lowers readability so probably not worth it)

2022-09-24 12:37 UTC, fakob commented on src/utils/utils.ts
> +  if (socketArray.length > 0) {
There is a slight difference.
* If you try to connect to a node which does not have an input/output, you should not be able to -> undefined
* If you try to connect to a node which has an input/output, you should be connected regardless of if it is a perfect match or just whatever -> index

2022-09-24 12:38 UTC, fakob commented on src/classes/NodeClass.ts
> +  getPreferredInputSocketIndex(): number | undefined {
Good idea.

2022-09-24 12:38 UTC, fakob commented on src/nodes/table.tsx
> +  getPreferredInputSocketIndex(): number {
You are right

2022-09-25 15:55 UTC, fakob commented on src/utils/utils.ts
> +    // if the node has a preferredInputSocket (with no connection), use it
I have made it into a "oneliner", but broken it down into functions. This should cover both the readability and the performance aspect of it.

2022-10-01 08:22 UTC, magnificus approved these changes

2022-10-01 12:37 UTC, merged