Move trigger sockets out of socket array
fakob/plug-and-play pull request #150
Opened 2022-09-27 19:56 UTC by fakob

* I have introduced a nodeTriggerSocketArray, which is being used if you right click add a node trigger socket
  * Though it is still possible to use triggerType on normal inputs
  * The node trigger sockets are displayed on the top before the outputs
* I have updated the look of trigger types to be square
* I have updated the addTriggerInput function to also turn off "Update on change" as this is probably always what you want when adding a nodeTriggerSocket

<img width="742" alt="Screen Shot 2022-09-27 at 21 52 10" src="https://user-images.githubusercontent.com/4619772/192622546-8879b71a-b996-46f6-bf1d-f493d883f0f6.png">

2022-09-28 20:00 UTC, magnificus requested changes
Nice, looking forward to trying it, added some comments about how we can reduce conditionals in the code

2022-09-28 20:00 UTC, magnificus commented on src/classes/NodeClass.ts
> -  addSocket(socket: Socket): void {
can we make a new function for this instead? so we dont have to pass in these conditionals to function

2022-09-28 20:00 UTC, magnificus commented on src/classes/NodeClass.ts
> +      const mapSocket = (item: SerializedSocket, isNodeTrigger = false) => {
again lets not pass in this conditional to all of our functions if we can avoid it

2022-09-28 20:00 UTC, magnificus commented on src/classes/NodeClass.ts
> +  getAllSockets(includeNodeTriggerSocketArray = true): Socket[] {
Would recommend making a new function, maybe rename the old one to getDataSockets()

and then getAllSockets() returns getDataSockets().concat(this.nodeTriggerSocketArray

2022-09-29 16:20 UTC, fakob commented on src/classes/NodeClass.ts
> -  addSocket(socket: Socket): void {
sounds good

2022-09-29 16:22 UTC, fakob commented on src/classes/NodeClass.ts
> +      const mapSocket = (item: SerializedSocket, isNodeTrigger = false) => {
I suggest to leave the top-level conditional for the mapSocket. This function is only local. It was introduced to not have to duplicate code, which I would have to do if I make 2 unique ones.

2022-09-29 16:22 UTC, fakob commented on src/classes/NodeClass.ts
> +  getAllSockets(includeNodeTriggerSocketArray = true): Socket[] {
Good idea!

2022-09-30 10:17 UTC, magnificus commented on src/classes/NodeClass.ts
> +      const mapSocket = (item: SerializedSocket, isNodeTrigger = false) => {
OK it is only local i see, then ait

2022-09-30 10:17 UTC, magnificus approved these changes

2022-09-30 14:45 UTC, merged