Switch to glide data grid 2
fakob/plug-and-play pull request #153
Opened 2022-10-09 19:22 UTC by fakob

* Switched to https://github.com/glideapps/glide-data-grid
* Removed CSV output option
* Changed preferredCondition to also work if the socket is hidden
* Fixed an issue with getMatchingSocket function

Known issues:
* Currently it is not possible to manually add rows or columns
* Pasting data into the grid, does not support adding more rows or columns in case it is needed

2022-10-10 19:13 UTC, magnificus requested changes

2022-10-10 19:13 UTC, magnificus commented on package.json
> +    "lodash": "^4.17.21",
do we need both lodash and lodash contrib? could we lose one of them?

2022-10-10 19:13 UTC, magnificus commented on src/utils/utils.ts
> +  if (lowerLimit < upperLimit) {
can be rewritten to lose the branch, would make the function like this

min = Math.min(lowerLimit, upperLimit)
max = Math.max(lowerLimit,upperLimit)

return Math.min(Math.max(min,value), value)

Better to not check for null and crash instead of something tries to do something so illegal

2022-10-10 19:13 UTC, magnificus commented on src/utils/utils.ts
> +export const getLongestArrayInArray = (arrayOfArrays): number => {
return 0 instead of undefined, and there is no need to branch here, just give the reduce a default value, this function can probably be just one line

2022-10-10 19:53 UTC, magnificus commented on src/nodes/table.tsx
> +        if (props.doubleClicked) {
should this be in the hybrid node base class?

2022-10-10 20:00 UTC, fakob commented on package.json
> +    "lodash": "^4.17.21",
lodash is a peer dependency of the data grid. lodash contrib is as far as I know, an additional package. They are not the same.

2022-10-10 20:02 UTC, fakob commented on src/utils/utils.ts
> +  if (lowerLimit < upperLimit) {
Nice. will do

2022-10-10 20:57 UTC, magnificus commented on package.json
> +    "lodash": "^4.17.21",
hmm if its a peer dependency wouldnt it be just in the lock file? I might be wrong

2022-10-15 12:51 UTC, magnificus approved these changes

2022-10-15 13:26 UTC, merged