Fix trigger socket not being removed and resize issue
fakob/plug-and-play pull request #174
Opened 2022-11-13 11:04 UTC by fakob

Fixes
* trigger sockets not actually being removed
* the node not resizing, when removing sockets in general

2022-11-13 17:06 UTC, magnificus commented on src/classes/GraphClass.ts
> +    //check nodeTriggers
these three blocks are super similar (copy pasted), could we make a common function that they all use?

2022-11-13 17:06 UTC, magnificus commented on src/classes/SocketClass.ts
> +    this.getNode().nodeTriggerSocketArray =
what about just concating nodetriggersocketarray with the normal socket array here? to avoid copy pasting

2022-11-13 17:07 UTC, magnificus requested changes
added two comments, copy paste concerns

2022-11-14 22:32 UTC, fakob commented on src/classes/GraphClass.ts
> +    //check nodeTriggers
Makes sense. Will do

2022-11-14 22:32 UTC, fakob commented on src/classes/SocketClass.ts
> +    this.getNode().nodeTriggerSocketArray =
The way this was written was that new nodeTrigger and input socket arrays are written, filtering out the destroyed one. This has to be done separate. 
I guess I could write a separate function which finds the socket and returns the array and then call it for
* nodeTriggerSocketArray
* inputSocketArray
* outputSocketArray
This would avoid the copy pasting at least.

2022-11-15 21:03 UTC, fakob commented on src/classes/GraphClass.ts
> +    //check nodeTriggers
Updated, though I did not know of another way then using the name strings of the array. @magnificus is that ok, or is there a better way to do this?

2022-11-15 21:03 UTC, fakob commented on src/classes/SocketClass.ts
> +    this.getNode().nodeTriggerSocketArray =
Same here. Please check

2022-11-15 21:25 UTC, magnificus commented on src/classes/GraphClass.ts
> +    //check nodeTriggers
What about this?

function checkAndUpdateSocketArray(oldArray, newArray) : void {
   oldArray.forEach((socket,index) => this.checkOldSocketAndUpdateIt(socket,newArray[index])
}

checkAndUpdateSocketArray(oldNode.nodeTriggerSocketArray, newNode.nodeTriggerSocketArray)
checkAndUpdateSocketArray(oldNode.inputSocketArray, newNode.inputSocketArray)
checkAndUpdateSocketArray(oldNode.outputSocketArray, newNode.outputSocketArray)

this can be further reduced but just this is much better IMO

for more minimal (but maybe harder to understand):

function checkAndUpdateSocketArray(oldNode, newNode, field) : void {
   oldArray[field].forEach((socket,index) => this.checkOldSocketAndUpdateIt(socket,newNode[field][index])
}

["nodeTriggerSocketArray", "inputSocketArray", "outputSocketArray"].forEach(field => checkAndUpdateSocketArray(oldNode,newNode,field);


etc.

2022-11-15 21:26 UTC, magnificus commented on src/classes/SocketClass.ts
> +    this.getNode().nodeTriggerSocketArray =
strategies above should work here too I think

2022-11-16 20:27 UTC, fakob commented on src/classes/SocketClass.ts
> +    this.getNode().nodeTriggerSocketArray =
I tried, but it did not work. The array is filtered and its variable is then overwritten. When I write a function which takes this array variable, it seems that I can not overwrite it within the function.

2022-11-16 20:27 UTC, fakob commented on src/classes/GraphClass.ts
> +    //check nodeTriggers
done

2022-11-16 20:36 UTC, magnificus commented on src/classes/SocketClass.ts
> +    this.getNode().nodeTriggerSocketArray =
the field thing should work here, but at the very least, lets make 
"socket.name === this.name && socket.socketType === this.socketType"

into a common function

2022-11-16 20:36 UTC, magnificus commented on src/classes/SocketClass.ts
> +    this.getNode().nodeTriggerSocketArray =
This would probably be better on the node as a function

RemoveSocket(socketin)

2022-11-17 21:32 UTC, fakob commented on src/classes/SocketClass.ts
> +    this.getNode().nodeTriggerSocketArray =
Moved it onto the node level

2022-11-18 19:59 UTC, magnificus approved these changes

2022-11-18 21:13 UTC, merged