Add dropdown widget
fakob/plug-and-play pull request #182
Opened 2022-11-19 20:21 UTC by fakob

* Added a dropdown widget with single and multi select option
* Added label option to all widgets

<img width="346" alt="Screenshot 2022-11-19 at 21 20 56" src="https://user-images.githubusercontent.com/4619772/202870026-75ec3c11-5058-475c-bf73-1f6ac765a878.png">

2022-11-20 10:31 UTC, magnificus requested changes
Very cool, just some things on the structure of the node

2022-11-20 10:31 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +    if (customArgs?.initialData) {
this looks more generic than for this node, should this be in the nodeclass? initialdata, I imagine this is copy pasted in other nodes as well

2022-11-20 10:31 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +      console.log(customArgs?.initialData);
also remove log

2022-11-20 10:31 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +      const options = this.getInputData(optionsName) || defaultOptions;
remove "||" and instead make sure this.getInputData(optionsName) always returns something valid

2022-11-20 10:31 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +    this.onNodeAdded = () => {
rewrite this as public onNodeAdded(): void { etc.

2022-11-20 10:31 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +    this.update = (): void => {
rewrite this as public update(): void {

2022-11-20 10:31 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +    this.onNodeResize = () => {
same for these, dont save down a callback function into a variable, instead just define them on the base object like normal functions

2022-11-20 10:31 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +    this.onExecute = async function () {
same here etc. etc.

2022-11-20 12:06 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +      const options = this.getInputData(optionsName) || defaultOptions;
This I had added because I can't control what the user inputs or another node inputs. Otherwise I would have to handle it in the react component. Is that better?

2022-11-20 12:11 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +      const options = this.getInputData(optionsName) || defaultOptions;
Wouldnt it always be an array? is it an arraytype? If so, can add parsing in the arrayType.parse

2022-11-23 19:28 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +      const options = this.getInputData(optionsName) || defaultOptions;
I guess that is a general question. You are right, we can fix this for the arraytype, but if the user changes the type to something else, which is possible, then it could potentially be undefined.
Should we not make sure that a node can handle undefined independently?

2022-11-23 20:35 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +      const options = this.getInputData(optionsName) || defaultOptions;
I think it is better to not handle null here, if so then every node has to do it, there is a parse function on the type which can be used to transform even null to for example an empty array, its on the datatypeclass

2022-11-23 20:56 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +    if (customArgs?.initialData) {
I have now moved it into the nodeclass. This required changes also in other nodes. Mainly hybridnodes.

2022-11-23 20:57 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +      console.log(customArgs?.initialData);
Done

2022-11-23 20:59 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +      const options = this.getInputData(optionsName) || defaultOptions;
If this is what we always want, we should then update the parsing function for all types to always give a valid value. 
Should I do that in this task?

2022-11-23 20:59 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +    this.onNodeAdded = () => {
done

2022-11-23 20:59 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +    this.update = (): void => {
done

2022-11-23 20:59 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +    this.onNodeResize = () => {
done

2022-11-23 21:00 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +    this.onExecute = async function () {
done

2022-11-23 21:01 UTC, magnificus commented on src/classes/NodeClass.ts
> +  initialData: any;
we don't have to persist this initialdata do we? Just use in constructor then disregard

2022-11-23 21:04 UTC, magnificus approved these changes
It looks good I think, apart from persisting intialdata, can we remove it as a field on node? Functions do not look like normal function definitions but won't harass you about that, thanks for doing this!

2022-11-23 21:05 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +      const options = this.getInputData(optionsName) || defaultOptions;
don't have to do it in this task if you don't want, as long as we plan for it :)

2022-11-27 22:35 UTC, fakob commented on src/classes/NodeClass.ts
> +  initialData: any;
Maybe I misunderstood, but I was basing this change on this comment:
> this looks more generic than for this node, should this be in the nodeclass? initialdata, I imagine this is copy pasted in other nodes as well

I can change it back again, having the initialData only on the node instances which need it. The persisting of data is necessary for hybrid nodes though. Also, this would mean that I have to change some of the public onNodeAdded functions back into the constructor again.

2022-11-29 19:07 UTC, magnificus commented on src/classes/NodeClass.ts
> +  initialData: any;
I see, I think we are struggling because of some structural issue here, what about adding it to the hybridnode only?

2022-11-29 21:34 UTC, merged