Improve inspector part 2
fakob/plug-and-play pull request #214
Opened 2023-01-15 21:26 UTC by fakob

Based on your comments, this is another update to the inspector with the following features:
* the properties of a node can now be filtered using "tabs"
  * Common
    * also visible if there are multiple nodes selected
    * currently it only contains update behaviour, but could in the future also show color, size, type, or other configs
  * Triggers - trigger sockets - only visible if there is a trigger socket
  * In - input sockets
  * Out - output sockets
  * Source - node config and class code
    * Regarding node config
      * added a "Replace" button , which allows you to edit the config source and replace. I did not know how to keep the id, so the updated node gets a new id
      * added a "New" button which just creates a new node without replacing
* rename the node editing the name in the header

I also made some other small changes
* code editors in the inspector now only load the first 1000 characters. this might reduce the loading weight and reduces also scrolling when scrolling through the sockets in the inspector
* removed the floating node menu as all functionality is now available in the inspector
* added a deselect node short cut - ctrl-shift-a
* made the text on the color widget use a contrast color

https://user-images.githubusercontent.com/4619772/212568141-9adbdb5b-3291-44e5-a0b5-c925ef247108.mov

<img width="318" alt="Screenshot 2023-01-15 at 22 24 21" src="https://user-images.githubusercontent.com/4619772/212568069-9aaa1056-9a1a-4b28-9ca8-9c48fc171a7e.png">

2023-01-16 19:38 UTC, magnificus commented on src/PropertyArrayContainer.tsx
>      return (
bunch of checks here, a bit ugly, why would filter be null? cant it be something else instead? Also, why would sockets be null? it should be [] if there are no sockets

2023-01-16 19:39 UTC, magnificus commented on src/PropertyArrayContainer.tsx
> +    props.selectedNodes.length > 0 ? props.selectedNodes?.[0] : null;
selectednodes should never be null, dont need to do ?.

2023-01-16 19:40 UTC, magnificus commented on src/PropertyArrayContainer.tsx
> +            props.filter == null) && (
once again would really like to avoid nullfilter, instead do a filter that allows everything through as default

2023-01-16 19:40 UTC, magnificus commented on src/PropertyArrayContainer.tsx
> +              {(props.filter === 'source' || props.filter == null) && (
same here etc etc

2023-01-16 19:41 UTC, magnificus commented on src/classes/GraphClass.ts
> +    if (newType && newSerializedNode === undefined) {
why do we need to check newSerializedNode against undefined here? its not used in expression

2023-01-16 19:42 UTC, magnificus commented on src/components/ResponsiveDrawer.tsx
> +        {props.selectedNodes?.length > 0 ? (
replace with just props.selectedNodes.length (dont need to have a comparator)

2023-01-16 19:43 UTC, magnificus commented on src/InspectorContainer.tsx
> +        {props.selectedNodes.length === 1 ? (
this expression is very big, can it be replaced with two functions instead maybe?

2023-01-16 19:44 UTC, magnificus commented on src/InspectorContainer.tsx
> +        {props.selectedNodes.length === 1 && (
this and the logical expression below have a lot in common, combine them to the extent its possible

2023-01-16 19:47 UTC, magnificus requested changes
Looks very promising (especially glad about red lines), but Im hoping we can lose some of the many branching conditionals we have now, the more conditions and if's the higher the risk one of them leads to bugs

2023-01-16 20:49 UTC, fakob commented on src/PropertyArrayContainer.tsx
>      return (
The ToggleButtonGroup MUI component returns null in this setup.

<img width="818" alt="Screenshot 2023-01-16 at 21 47 31" src="https://user-images.githubusercontent.com/4619772/212763419-b2b0b748-7960-49ab-b2fd-3c4b0e510151.png">

2023-01-16 20:51 UTC, fakob commented on src/PropertyArrayContainer.tsx
>      return (
Ah, yes you are right, the socket should always be [].

2023-01-16 20:54 UTC, fakob commented on src/PropertyArrayContainer.tsx
> +            props.filter == null) && (
As mentioned above. Null is what I get back from the component. I can map the null value to another value, for example, "showAll", but I would still need to check for either "common" or "showAll". Is that better?

2023-01-16 21:03 UTC, fakob commented on src/classes/GraphClass.ts
> +    if (newType && newSerializedNode === undefined) {
newSerializedNode is a new optional parameter I have added. And only if you are passing in a newType, but not if you pass in a newSerializedNode, you should rename the node to its type. So in essence you can either replace something using
* a newType
* OR a newSerializedNode
Would it be better to only use one optional parameter? `new?:string | SerializedNode`? and then check if it is a string or a SerializedNode doing logic based on that?

2023-01-16 21:05 UTC, fakob commented on src/components/ResponsiveDrawer.tsx
> +        {props.selectedNodes?.length > 0 ? (
Done

2023-01-16 21:05 UTC, fakob commented on src/PropertyArrayContainer.tsx
> +    props.selectedNodes.length > 0 ? props.selectedNodes?.[0] : null;
done

2023-01-16 21:19 UTC, fakob commented on src/InspectorContainer.tsx
> +        {props.selectedNodes.length === 1 ? (
Good catch. Done.

2023-01-16 21:19 UTC, fakob commented on src/InspectorContainer.tsx
> +        {props.selectedNodes.length === 1 && (
Splitting them apart as of above request, helped to also make this cleaner.

2023-01-23 18:51 UTC, magnificus approved these changes

2023-01-23 19:09 UTC, merged