Socket click to focus
fakob/plug-and-play pull request #218
Opened 2023-01-29 20:26 UTC by fakob

* When clicking on a socket
  * the inspector opens
  * switches to the respective filter
  * scrolls to and marks the socket
* moved the toast messages to appear in the center, to not cover the drawer button
* moved the share button to the top left

https://user-images.githubusercontent.com/4619772/215353983-baccb990-f80a-4988-9960-c49baa60cf0e.mov

2023-01-29 20:38 UTC, magnificus commented on src/PropertyArrayContainer.tsx
> +    switch (true) {
I feel like there is a more elegant way to do this, cant you ask the socket iself what type it is? then it also does not have to be passed into socketArrayToComponent

2023-01-29 20:39 UTC, magnificus requested changes
Looks ait and the feature is very useful BUT left a comment on a part in the middle where I think implementation can be different to reduce dependencies and number of lines

2023-01-29 21:57 UTC, fakob commented on src/PropertyArrayContainer.tsx
> +    switch (true) {
I am not sure that actually works. The filter has to be set outside socketArrayToComponent. However, I have now moved the checking in which array the socket is to the socketClass. Please review again.

2023-01-30 20:25 UTC, magnificus commented on src/classes/SocketClass.ts
> +    switch (true) {
you already know what type the socket is, so no need to go up to the parent to check, check yourself whether you are IN OUT or TRIGGER instead

2023-01-31 21:24 UTC, magnificus commented on src/classes/NodeClass.ts
> +  getInputOrTriggerSocketByName(slotName: string): Socket {
might be problematic if there is a name collision between triggers and input

2023-01-31 21:27 UTC, magnificus approved these changes
Looking good!

2023-01-31 21:51 UTC, fakob commented on src/classes/NodeClass.ts
> +  getInputOrTriggerSocketByName(slotName: string): Socket {
You are right. Not sure how to solve this though. The Triggers are called Trigger 1, 2 etc. Maybe let's try to not call any normal input Trigger 1?

2023-01-31 21:57 UTC, merged