Unsaved changes warning
fakob/plug-and-play pull request #223
Opened 2023-02-03 19:21 UTC by fakob

* Added an unsaved changes warning when
  * closing or reloading a tab/window -> shows standard close/reload tab browser dialog (no control over design or text)
  * loading another graph -> shows the browsers default confirmation dialog (no control over design)
    * for this case we can add a react modal dialog in the future to make it prettier

<img width="272" alt="Screenshot 2023-02-03 at 20 20 29" src="https://user-images.githubusercontent.com/4619772/216689183-0ec1294c-c31e-4231-b517-d3f17f152d24.png">
<img width="277" alt="Screenshot 2023-02-02 at 22 12 20" src="https://user-images.githubusercontent.com/4619772/216688404-301c4a9f-3dd0-4455-bf69-d2d9080654cc.png">
<img width="461" alt="Screenshot 2023-02-03 at 20 16 05" src="https://user-images.githubusercontent.com/4619772/216688406-209b262c-be4a-4cd6-90a8-363b06a663a3.png">

2023-02-04 19:32 UTC, magnificus commented on src/PPStorage.tsx
> +      console.log(fileData);
can remove log

2023-02-04 19:34 UTC, magnificus commented on src/classes/GraphClass.ts
> +  onBeforeUnload(event: BeforeUnloadEvent): string {
not very clear what this function does, can it be made more explicit?

2023-02-04 19:35 UTC, magnificus commented on src/classes/GraphClass.ts
> +  private unsavedChanges: boolean;
could this instead be stored inside actionHandler? graphHasUnsavedChanges? cleaner to not expose implicit property this to the graph

2023-02-04 19:35 UTC, magnificus commented on src/utils/actionHandler.tsx
> +    PPGraph.currentGraph.setUnsavedChange(true);
lets keep it inside actionhandler instead if possible

2023-02-04 19:36 UTC, magnificus requested changes
Looks good and useful, but would strongly suggest putting the hasChanges variable inside action handler instead, to not let the graph know anything about how it is saved and why etc.

2023-02-05 16:32 UTC, fakob commented on src/classes/GraphClass.ts
> +  onBeforeUnload(event: BeforeUnloadEvent): string {
added a comment

2023-02-05 16:32 UTC, fakob commented on src/PPStorage.tsx
> +      console.log(fileData);
done

2023-02-05 16:33 UTC, fakob commented on src/classes/GraphClass.ts
> +  private unsavedChanges: boolean;
moved it to the actionhandler

2023-02-05 21:10 UTC, magnificus commented on src/PPStorage.tsx
> +        await this.db.settings.put({
we should have a function "setLoadedGraphID" and "getLoadedGraphID" on PPStorage that does this, so we can hide the name in DB

2023-02-05 21:11 UTC, magnificus approved these changes

2023-02-06 19:24 UTC, fakob commented on src/PPStorage.tsx
> +        await this.db.settings.put({
done

2023-02-06 19:24 UTC, merged