Fix add connected widget nodes
fakob/plug-and-play pull request #276
Opened 2023-06-02 19:50 UTC by fakob

When right clicking on an input socket text you are able to choose a "widget" node. For the codeEditor and the Label we were carrying over the text from the input socket. Now I have implemented that
* this also works for other widgets like the slider, the trigger, the color picker, ...
* not just data get's carried over but also other properties
  * the socket name in case the widget has a label
  * the min, max, round values in case of the slider widget

Currently this behaviour is only triggered if right clicking the socket name and choosing the widget from their. I wonder if we should make it work in general when dragging a connection from an input socket and choosing an appropriate widget from the search.

<img width="1063" alt="Screenshot 2023-06-02 at 21 44 21" src="https://github.com/fakob/plug-and-play/assets/4619772/b488f37d-98cb-4af7-ba95-f74b3f4b7b9b">

2023-06-04 14:39 UTC, magnificus commented on src/classes/GraphClass.ts
> +          initialData: socket.isInput() ? socket : undefined,
a socket as initial data sounds crazy, do we need this?

2023-06-04 14:40 UTC, magnificus commented on src/nodes/codeEditor.tsx
> +  public onNodeAdded = (source?: TNodeSource) => {
this looks pretty messy, should we talk about how things are working here?

2023-06-04 14:40 UTC, magnificus commented on src/nodes/data/dataFunctions.tsx
> +      let data;
looks messy and also copy pasted from above

2023-06-04 14:40 UTC, magnificus commented on src/nodes/text.tsx
> +      let data;
same

2023-06-04 14:41 UTC, magnificus requested changes
Hate to say it but this code looks very unhealthy, can we discuss it?

2023-06-04 17:20 UTC, fakob commented
I think the feature is very important, but I was also not happy with the solution. I hope we find a better implementation. Let's discuss

2023-06-04 21:08 UTC, magnificus commented
Yes, sounds good

Den sön 4 juni 2023 19:20Jakob Schindegger ***@***.***> skrev:

> I think the feature is very important, but I was also not happy with the
> solution. I hope we find a better implementation. Let's discuss
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fakob/plug-and-play/pull/276#issuecomment-1575646049>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA57IOQPFIE7TZ7PGZOHVQLXJS7XTANCNFSM6AAAAAAYYXHDHM>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-06-07 18:08 UTC, magnificus commented on src/nodes/data/dataFunctions.tsx
> +  public outputPlugged(): void {
this looks copy pasted from the one above, would make them use the same code

2023-06-07 18:20 UTC, fakob commented on src/nodes/codeEditor.tsx
> +      links.length === 1 &&
Ah, you are right. Will do

2023-06-09 20:05 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +      target.dataType.constructor === new ArrayType().constructor &&
would avoid checking for the class here, in general checking for class is considered an anti-pattern, I would recommend the Array.isArray function

2023-06-09 20:07 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +      target.dataType.constructor === new ColorType().constructor &&
would recommend something like isColor instead of checking class, consider if it is an AnyType that contains a color for example.

2023-06-09 20:07 UTC, magnificus commented on src/nodes/widgets/widgetNodes.tsx
> +      target.dataType.constructor === new ArrayType().constructor &&
same comment as above

2023-06-09 20:07 UTC, magnificus approved these changes
I like the feature a lot, but added a few more comments

2023-06-10 09:03 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +      target.dataType.constructor === new ArrayType().constructor &&
makes sense

2023-06-10 09:03 UTC, fakob commented on src/nodes/widgets/widgetNodes.tsx
> +      target.dataType.constructor === new ColorType().constructor &&
good idea

2023-06-10 09:03 UTC, merged