Add tooltips
fakob/plug-and-play pull request #297
Opened 2023-08-05 17:19 UTC by fakob

* Added tooltips when hovering over socket, node, selection
  * Selection node and input socket tooltips are shown on the left side, output sockets are shown on the right side
* When hovering over socket, changed option from ctrl+click to shift+click to pin the inspector (currently only one floating inspector is allowed)
  * Shift click now also works when over the actual socket, not just the text
* Added option to show the node inspector to the socket context menu

https://github.com/fakob/plug-and-play/assets/4619772/3881bcc7-773d-4e5e-94fc-1f53f92a712e

<img width="252" alt="Screenshot 2023-08-05 at 18 55 20" src="https://github.com/fakob/plug-and-play/assets/4619772/31dc833e-9636-4c8b-bdd2-ed152edd554a">
<img width="791" alt="Screenshot 2023-08-05 at 18 56 23" src="https://github.com/fakob/plug-and-play/assets/4619772/21f7d8f1-9102-42cf-8363-c6b4220a10c7">
<img width="500" alt="Screenshot 2023-08-05 at 18 56 33" src="https://github.com/fakob/plug-and-play/assets/4619772/6ee802e6-e308-4723-8ef4-8aac896b848b">

2023-08-06 13:25 UTC, magnificus commented on src/classes/NodeClass.ts
> +    PPGraph.currentGraph.viewport.addEventListener(
Can this be done via interfacecontroller instead?

2023-08-06 13:29 UTC, magnificus commented on src/components/Tooltip.tsx
> +    case isSocket(object):
instead of switch casing in here, could we make an interface for "TooltipBehaviour" that both node and socket implements? (Makes it more scalable and separation of concerns)

2023-08-06 13:30 UTC, magnificus commented on src/components/Tooltip.tsx
> +function Content(props) {
Can we make this return type static and optional if we need to return null?

function Content(props) : ReactSomething | | undefined

2023-08-06 13:31 UTC, magnificus commented on src/components/Tooltip.tsx
> +      return null;
if possible to avoid null and instead do empty component or something it is more elegant, but no big deal

2023-08-06 13:31 UTC, magnificus commented on src/utils/utils.ts
> +export function getSocket(socketish): PPSocket {
lets get rid of these and instead work with classes and children, this is very hacky

2023-08-06 13:32 UTC, magnificus commented on src/utils/utils.ts
> +    case isSocket(object):
yeah same with these

2023-08-06 13:32 UTC, magnificus requested changes
Looks very promising but we need to drop the case switch behaviour and work with an interface instead

2023-08-07 17:01 UTC, fakob commented on src/classes/NodeClass.ts
> +    PPGraph.currentGraph.viewport.addEventListener(
Done, though I had introduce a new one as I only need `pointerup` and not also `pointerupoutside`

2023-08-07 17:01 UTC, fakob commented on src/components/Tooltip.tsx
> +    case isSocket(object):
Done

2023-08-07 17:02 UTC, fakob commented on src/components/Tooltip.tsx
> +      return null;
Done

2023-08-07 17:02 UTC, fakob commented on src/utils/utils.ts
> +export function getSocket(socketish): PPSocket {
Done

2023-08-07 17:02 UTC, fakob commented on src/utils/utils.ts
> +    case isSocket(object):
Done

2023-08-07 17:44 UTC, magnificus requested changes
Nice, you have understood the idea, you have just implemented it in a very unorthodox way. The normal way to implement it would be to create a new abstract class https://www.tutorialsteacher.com/typescript/abstract-class called something like "TooltipAble", which has a single abstract function "getTooltipContent".

Then on NodeClass and SocketClass you would extend this class, and as the function in "TooltipAble" is abstract, it won't compile until you make a function in them that matches. Then in the check you are doing now, instead of checking for if the function exists, you would check if the object implements "TooltipAble"

2023-08-07 18:48 UTC, magnificus approved these changes

2023-08-07 19:23 UTC, merged