Add node browser
fakob/plug-and-play pull request #317
Opened 2023-10-24 15:53 UTC by fakob

* Added a node browser which
  * shows all nodes in a graph
    * nodes with errors and macros are on top
  * hovering over a node in the list shows a focus border around the node in the graph
  * clicking on a node in the list centers the node
  * double clicking on a node in the list centers and zooms in onto the node
  * clicking the select node button on a node in the list, selects the node
  * using the arrow in the top of the drawer, let's you go back to the node browser
  * the INFO tab shows
    * a description we can add in the future
    * the JSON of the graph which can be edited and with the replace button be loaded again
* Changed the default name of a node on creation to NOT be the node type, but the given name (getName())
* Updated the "missing nodes test" example

https://github.com/fakob/plug-and-play/assets/4619772/c8687cd4-7bcc-421a-a86f-94ac6824ce41

2023-10-24 17:04 UTC, magnificus requested changes
It looks very promising and looking forward to trying it, but some mess in the code we should do a second sweep on

2023-10-24 17:04 UTC, magnificus commented on src/NodeArrayContainer.tsx
> +    if (!a.successfullyExecuted && b.successfullyExecuted) return -1;
This sorting can be described more elegantly for example via something like

Return 100 * (a.successexec - bsuccessexec) + 10 * (a.type == macro ...) ...

2023-10-24 17:04 UTC, magnificus commented on src/NodeArrayContainer.tsx
> +    const newSelectedNode =
These long and anxious statements are a bit confusing and ugly, code should know what is coming in here

2023-10-24 17:04 UTC, magnificus commented on src/NodeArrayContainer.tsx
> +        {(props.filter === 'nodes' || props.filter == null) && (
Same with all these null checks

2023-10-25 16:10 UTC, fakob commented on src/GraphInspectorContainer.tsx
> +  const [graphName, setGraphName] = React.useState('');
If I should pass it as a prop here I would need to get it somewhere up the chain and pass it down. But then I need the state somewhere up there. I don't think I can move the function to get the name into a prop, as it returns a promise.

2023-10-26 15:08 UTC, fakob commented on src/InspectorContainer.tsx
> +        >
You are right, I was lazy when I had done that. Will fix

2023-10-26 15:15 UTC, fakob commented on src/InspectorContainer.tsx
I need a state when editing so the updating works, but I can move it into the header component now

2023-10-26 15:22 UTC, fakob commented on src/InspectorContainer.tsx
> +      {props.selectedNodes[0].name !== props.selectedNodes[0].getName() && (
will do

2023-10-26 15:35 UTC, fakob commented on src/NodeArrayContainer.tsx
> +          if (event.detail === 2) {
Good point. It refers to double and tripple click on an onclick event. Will do

2023-10-26 15:49 UTC, fakob commented on src/NodeArrayContainer.tsx
> +  const [selectedNode, setSelectedNode] = useState(singleNode);
Actually, good catch. The selectedNode is not needed here at all. Was a leftover from before. Will remove.

2023-10-26 16:21 UTC, fakob commented on src/NodeArrayContainer.tsx
> +    if (!a.successfullyExecuted && b.successfullyExecuted) return -1;
Ah, good idea.

2023-10-26 16:32 UTC, fakob commented on src/NodeArrayContainer.tsx
> +    const newSelectedNode =
removed it, as mentioned above

2023-10-26 16:32 UTC, fakob commented on src/NodeArrayContainer.tsx
> +        {(props.filter === 'nodes' || props.filter == null) && (
Sounds good

2023-10-26 17:53 UTC, magnificus commented on src/GraphInspectorContainer.tsx
> +  const [graphName, setGraphName] = React.useState('');
but we are using graph name in other components as well right? Could they refer to the same place?

2023-10-26 17:55 UTC, magnificus approved these changes

2023-10-29 15:48 UTC, merged