Update parsing with warning
fakob/plug-and-play pull request #342
Opened 2023-11-19 12:15 UTC by fakob

This is the first step of updating parsing.
* now parsing a value always returns a valid value of the specific data type
* in case there are errors in the parsing, we include a warning
  * for now I have used only a single string at the moment, but can be made into an array in the future
* currently it only triggers a warning log. In the second part I will trigger an Error from the Error class and show this warning somewhere. This is the second step

2023-11-19 21:56 UTC, magnificus requested changes
looks promising and good conceptually but have some input on code

2023-11-19 21:56 UTC, magnificus commented on src/nodes/datatypes/arrayType.tsx
> +
instead of all these lines, at the end, do:

if (parsedData == undefined){
 warnings.push(new NodeTypeWarning('Not an array. [] is returned'))
 parsedData = []

}

2023-11-19 21:56 UTC, magnificus commented on src/nodes/datatypes/abstractType.tsx
> +  parse(data: any): TParseType {
good with a type

2023-11-19 21:56 UTC, magnificus commented on src/utils/interfaces.tsx
> +export type TParseType = {
instead of this I would make it

{
value : any;
warnings[]: PNPWarningClass
}

This gives us two things, first, an array both allows more than one warning at a time, and avoids using null. The warning class allows us to add more behaviours and aligns with our error classes.

2023-11-19 21:56 UTC, magnificus commented on src/nodes/datatypes/colorType.tsx
>      if (typeof data === 'string') {
similar to above, can achieve desired result with fewer lines

2023-11-19 21:56 UTC, magnificus commented on src/nodes/datatypes/stringType.tsx
> +  if (data === null || data === undefined) {
same as further up, can use fewer lines

2023-11-19 21:56 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +    const { value: selectedColor, warning } = new ColorType().parse(
these lines in the draw nodes look copy pasted, turn into common function

2023-11-20 21:02 UTC, fakob commented on src/utils/interfaces.tsx
> +export type TParseType = {
Sounds good. I wanted to do this in the seconds step. But can also do it now.

2023-11-20 21:10 UTC, fakob commented on src/nodes/datatypes/arrayType.tsx
> +
Good idea

2023-11-20 21:14 UTC, fakob commented on src/nodes/datatypes/colorType.tsx
>      if (typeof data === 'string') {
will do

2023-12-04 18:07 UTC, fakob commented
There are 2 known limitations
* If a node is not updated, the warning only disappears if it is executed, or selected. Selecting triggers the PropertyArrayContainer > getConfigData > serialize > get data and is therefore updated/reparsed
* The errors/warnings in the node browser do not update unless you click in the graph to send unselect

2023-12-04 19:19 UTC, magnificus requested changes
Looks very promising, left some comments

2023-12-04 19:19 UTC, magnificus commented on src/SocketContainer.tsx
> +  const [hasError, setHasError] = useState(props.property.status.isError());
not a massive deal, points below are more important, you decide on this

2023-12-04 19:19 UTC, magnificus commented on src/classes/SocketClass.tsx
> +    const currentMessage = JSON.stringify(this.status.message);
isnt message always a string? if so dont need to stringify

2023-12-04 19:19 UTC, magnificus commented on src/nodes/api/chatgpt.tsx
> +    this.status.custom = [];
it seems like most of these only want one of these custom notifications at a time right? If so we could have a function on NodeClass "pushExclusiveCustomStatus", then we wouldnt need to set this.status.custom = [] manually everywhere we do this,

2023-12-04 19:19 UTC, magnificus commented on src/InterfaceController.ts
> +  onNodeStatusChanged, // data = node
might be easier to skip these, left comment further down

2023-12-05 16:59 UTC, fakob commented on src/NodeArrayContainer.tsx
> +      (+b.status.node.isError() - +a.status.node.isError()) * 1000 +
Using the + here is the easiest way to convert the boolean to a number for typescript. Or should I use a different way?

2023-12-05 17:30 UTC, fakob commented on src/classes/NodeClass.tsx
> +      if (Array.isArray(this.status[key])) {
The `status` on the node itself is not a class, only the items inside. I am using this to get flatten this object/array combination. I can also do something like this:

const flattened = [];
this.status.node.isError && flattened.push(this.status.node);
this.status.socket.isError && flattened.push(this.status.socket);
flattened.push(...this.status.custom);

Is this better?

<img width="640" alt="Screenshot 2023-12-05 at 18 24 49" src="https://github.com/fakob/plug-and-play/assets/4619772/280319fb-0807-480f-81ae-b4ef12050438">

2023-12-05 17:31 UTC, fakob commented on src/classes/NodeClass.tsx
> +  doSocketsHaveErrors(): void {
Good idea

2023-12-05 17:35 UTC, fakob commented on src/classes/NodeClass.tsx
> +  public setStatus(status: PNPStatus, typeSocket = false) {
Good idea

2023-12-05 17:59 UTC, fakob commented on src/utils/utils.ts
> +export const parseValueAndAttachWarnings = (
Will do

2023-12-06 20:10 UTC, magnificus commented on src/NodeArrayContainer.tsx
> +    const newNnodeStatus = props.property.status.node as PNPStatus;
very minor, but typo on newNodeStatus

2023-12-06 20:13 UTC, magnificus approved these changes
Very cool, looks very useful

2023-12-06 20:45 UTC, fakob commented on src/NodeArrayContainer.tsx
> +    const newNnodeStatus = props.property.status.node as PNPStatus;
Wow, good catch!

2023-12-06 20:45 UTC, merged