allow header injection for html node
fakob/plug-and-play pull request #348
Opened 2023-12-06 21:36 UTC by fakob

* added a header socket which allows to add code in the header of the html node
  * as default example we are loading tailwind and style the text with it

<img width="632" alt="Screenshot 2023-12-06 at 22 35 46" src="https://github.com/fakob/plug-and-play/assets/4619772/1c34d802-d90f-4c91-850a-7c8a6d9c85c6">

2023-12-09 09:38 UTC, magnificus requested changes

2023-12-09 09:38 UTC, magnificus commented on src/nodes/draw/html.tsx
> -      if (iframeRef.current) {
when would this be invalid? can check be removed?

2023-12-09 09:38 UTC, magnificus commented on src/nodes/draw/html.tsx
> +      .find((socket) => socket.name === inputSocketNameHtml);
You can do this much more elegantly with inheritance, change defaultCode in the parent to

getDefaultHTMLCode() (or some other name), then in parent getDefaultIO

      new PPSocket(
        SOCKET_TYPE.IN,
        inputSocketNameHtml,
        new CodeType(),
        getDefaultHTMLCode(),
        false,

then in child just override

getDefaultHTMLCode() with
return `<iframe src="https://en.wikipedia.org/wiki/Special:Random" style="width: 100%; height: 100%;"></iframe>`

2023-12-11 19:14 UTC, fakob commented on src/nodes/draw/html.tsx
> +      .find((socket) => socket.name === inputSocketNameHtml);
Good idea!

2023-12-11 19:20 UTC, fakob commented on src/nodes/draw/html.tsx
> -      if (iframeRef.current) {
Good question. I think with the constructor update this is no longer an issue. Will remove.

2023-12-12 18:46 UTC, magnificus approved these changes

2023-12-12 18:56 UTC, merged