Add update on load
fakob/plug-and-play pull request #349
Opened 2023-12-07 21:36 UTC by fakob

* Added an "Update on load" option which executes the node after everything has been loaded
  * This is helpful for nodes like the HTTP node or Custom functions which should be executed once the graph is loaded, but which you might not want to update always on change

This is different from "Execute on place" which is executed when nothing is connected. It makes sense to keep this hidden away from the user as some nodes rely on it.

<img width="514" alt="Screenshot 2023-12-07 at 22 30 30" src="https://github.com/fakob/plug-and-play/assets/4619772/52a14214-1ce0-4873-b6b2-265df39b651e">

2023-12-08 15:57 UTC, fakob commented
> This is different from "Execute on place" which is executed when nothing is connected. It makes sense to keep this hidden away from the user as some nodes rely on it.

As execute on place was, I guess, mainly fixing specific nodes which need to be executed once. This can probably, after your refactor, be done in the onNodeAdded function. Then we can get rid of execute on place I guess.

2023-12-09 09:40 UTC, magnificus commented on src/classes/NodeClass.tsx
> +    if (this.executeOnPlace()) {
can we get rid of executeonplace and instead use load now? :), alternatively, just make executeonplace return this value. But we also want to remove executeOnPlace in all children, and instead make them use the new load value

2023-12-09 09:40 UTC, magnificus requested changes
looks good, now we just want to get rid of remains from old system

2023-12-11 20:58 UTC, fakob commented on src/classes/NodeClass.tsx
> +    if (this.executeOnPlace()) {
Will do

2023-12-12 20:44 UTC, magnificus commented on src/classes/GraphClass.ts
> +        console.log(node.name);
can remove log

2023-12-12 20:45 UTC, fakob commented on src/classes/GraphClass.ts
> +        console.log(node.name);
just did :-)

2023-12-12 20:45 UTC, magnificus commented on src/classes/GraphClass.ts
> +        console.log(node.name);
BTW, you can probably combine this with the above one, so that we dont have to execute a potential node that is both seed node and load two times

2023-12-12 20:46 UTC, magnificus approved these changes
looks good now just one thing about potentially having to execute some initial nodes twice, not neccessary

2023-12-13 23:04 UTC, fakob commented on src/classes/GraphClass.ts
> +        console.log(node.name);
I will create a separate pull request for this.

2023-12-13 23:04 UTC, merged