noticed getConfig is super heavy for nodes with a bunch of data and i…
fakob/plug-and-play pull request #351
Opened 2023-12-09 18:32 UTC by magnificus

…ts called in interface, sped it up

there are more things I found I will fix

2023-12-10 13:24 UTC, magnificus commented on src/nodes/datatypes/jsonType.tsx
> -    if (typeof props.property.data !== 'string') {
this was setting the data on the socket itself to a stringified version on widget open, was costing a lot of performance and seemed very strange to me

2023-12-11 20:43 UTC, fakob requested changes
The point with the "Info" tab for both graph and node is that you can
* see its current config (serialized view)
* edit and replace it

I understand that it is not practical to serialize the graph or node every time you open the inspector, but then I suggest that we introduce a "load config" button in the "Info" tab, which would serialize the graph or node. Currently the config part of the info tab has lost its meaning as it does not show the current state.

<img width="363" alt="Screenshot 2023-12-11 at 21 34 30" src="https://github.com/fakob/plug-and-play/assets/4619772/1491e0a5-da73-4088-804d-7ae6eb5aa49d">

2023-12-12 17:45 UTC, magnificus commented
OK, load config button sounds good to me, would you be able to help me with that? will then remove the parameter to serialize "includeSockets"

2023-12-13 22:59 UTC, fakob commented
I have now pushed a change where the sourceContent is broken out into its own component and in there I have added a load data button. Please have a look.

<img width="338" alt="Screenshot 2023-12-13 at 23 33 42" src="https://github.com/fakob/plug-and-play/assets/4619772/3c898f08-5d5b-48aa-ab4c-e6e027d032a6">

2023-12-14 21:37 UTC, merged