Improve combine node 2
fakob/plug-and-play pull request #399
Opened 2024-03-18 21:43 UTC by fakob

This is a temporary PR, as I am still looking for the issue with the last item missing the override. Maybe you can have a look through if you see something obviously wrong?

2024-03-19 20:37 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +        addShallowContainerEventListeners(shallowContainer, this, i);
missing executions here, intended???

2024-03-19 20:37 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +    const margin = {
fairly certain something with this logic here is quacky, it looks very complex, im sure we can simplify it, this will likely also fix the bug

2024-03-19 20:38 UTC, magnificus commented on src/nodes/draw/abstract.tsx
> +      let bgX = -margin.left + myContainerBounds.x;
this does not look good I think

2024-03-19 20:46 UTC, fakob commented on src/nodes/draw/draw.tsx
> +        addShallowContainerEventListeners(shallowContainer, this, i);
executions is not used in the eventlistener, so I thought that I can remove it completely

2024-03-29 15:32 UTC, fakob commented
I have tried to keep the needed complexity completely within the combine node. Catering for this many options was challenging, but I think it is worth it.
* Updated the combine node and added the ability to
  * layout/position the inputs
    * manually (manual) - old behaviour
    * automatically separating them with a gap (gap)
    * automatically spreading them out between a fixed distance (spread)
  * set the direction of the layout (vertical or horizontal)
  * set the container size
    * based on the content size (hug)
    * based on the parent size (fill)
    * based on a fixed size (fixed)
  * align the inputs inside the container left/center/right, top/center/bottom
* Cleaned up abstract class
  * removed pivot (default pivot is now centered)
  * moved margin and background to combine node

<img width="937" alt="Screenshot 2024-03-29 at 16 32 00" src="https://github.com/fakob/plug-and-play/assets/4619772/1fc3280a-a654-412f-96c6-6356df06e1b6">

2024-03-31 15:13 UTC, magnificus requested changes
Looks promising and will maybe tie in well with the performance improvement (?) but left some comments

2024-03-31 15:13 UTC, magnificus commented on src/nodes/draw/abstract.tsx
> +    // example for passing in overrides
can remove

2024-03-31 15:13 UTC, magnificus commented on src/nodes/draw/abstract.tsx
> +  private handleDrawing(drawingFunction: any, inputObject): void {
inputobject not used? if so lets remove

2024-03-31 15:13 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +        if (parentBgWidth) {
avoid nullcheck here, we should be able to say with confidence that it exists

2024-03-31 15:13 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +        addShallowContainerEventListeners(shallowContainer, this, i);
OK

2024-03-31 15:13 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +    const bgColor = parseValueAndAttachWarnings(
this function looks super verbose, can we simplify it? We should at least be able to split this function into several smaller ones.

2024-03-31 17:39 UTC, fakob commented on src/nodes/draw/draw.tsx
> +        if (parentBgWidth) {
Well, the point is that `parentBgWidth` is only passed down/relevant when the parent is another combine node. However, the parent can be a multiplier node which does not pass this property down. In this case it just falls back to use the fixed with.

2024-03-31 17:39 UTC, fakob commented on src/nodes/draw/abstract.tsx
> +  private handleDrawing(drawingFunction: any, inputObject): void {
will do

2024-03-31 17:39 UTC, fakob commented on src/nodes/draw/abstract.tsx
> +    // example for passing in overrides
will do

2024-04-01 15:22 UTC, fakob commented on src/nodes/draw/draw.tsx
> +    const bgColor = parseValueAndAttachWarnings(
I had tried for some time to make it simpler, but due to its diverse functionality, I was not able to do that. I have now split certain parts into separate functions.

2024-04-01 19:25 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +              (predefinedBackgroundWidth -
same as comment above

2024-04-01 19:26 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +                padding.top + predefinedBackgroundHeight - bounds.height / 2;
one idea, is it possible to turn bounds or predefinedBackgroundHeight into something like a "heightToUse" varialble? then the difference could happen up there and dont need to diverge paths here

2024-04-11 19:36 UTC, magnificus commented on cypress/e2e/pnp/parallelizable/testCombineObjects.cy.ts
> +import { doWithTestController, openNewGraph } from '../helpers';
good with test

2024-04-11 19:36 UTC, magnificus commented on cypress/e2e/pnp/parallelizable/testCombineObjects.cy.ts
> +    cy.wait(100);
are these waits needed? cant we use the await toast thing instead?

2024-04-11 19:36 UTC, magnificus commented on cypress/e2e/pnp/parallelizable/testCombineObjects.cy.ts
> +    cy.wait(100);
same as above and below etc

2024-04-11 19:36 UTC, magnificus commented on src/TestController.ts
> +    console.log(coordinates);
remove log

2024-04-11 19:36 UTC, magnificus commented on src/components/ContextMenus.tsx
> +            <MenuItem
do you want the extract macro thing to be related to this draw node specific thing? Possible typo

2024-04-11 19:36 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +    drawingFunction.hash = () => newHash;
drawingFunction.hash = uuid

2024-04-11 19:36 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +    const bounds = DRAW_Get_Bounds.getDrawingBounds(
wondering, instead of setting the drawingfunction hash, you can just send in this UUID here into the getbrounds "callchain", a little cleaner.

2024-04-11 19:36 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +const bgColorName = 'Background color';
Because of how large and complex this is, can we move into a separate file?

2024-04-11 19:36 UTC, magnificus commented on src/nodes/draw/draw.tsx
> +    if (hasMarginOrBackground) {
I will approve PR, but because of how complex this is I likely wont be able to bugfix it if it would break

2024-04-11 19:36 UTC, magnificus commented on src/pixi/utils-pixi.tsx
> +    console.log(node.children[0].children[0]);
I would not use this function this way it looks quite messy, if you want to do this I recommend just changing it in utlils where it is called instead of making this function less predictable.

2024-04-11 19:56 UTC, fakob commented on cypress/e2e/pnp/parallelizable/testCombineObjects.cy.ts
> +    cy.wait(100);
I believe that I had issues when I ran `doWithTestController` back to back, but I can check again.

2024-04-11 19:56 UTC, fakob commented on src/components/ContextMenus.tsx
> +            <MenuItem
Good catch! That is a mistake.

2024-04-11 19:57 UTC, fakob commented on src/nodes/draw/draw.tsx
> +    drawingFunction.hash = () => newHash;
Ah yes.

2024-04-11 19:58 UTC, fakob commented on src/nodes/draw/draw.tsx
> +    const bounds = DRAW_Get_Bounds.getDrawingBounds(
The getDrawingBounds function uses the hash for lookup and not the callchain. I am not fully sure how your logic works, but I believe it did not update when I passed in the UUID as callchain.

2024-04-11 19:59 UTC, fakob commented on src/nodes/draw/draw.tsx
> +const bgColorName = 'Background color';
Good idea. Will do.

2024-04-11 19:59 UTC, fakob commented on src/pixi/utils-pixi.tsx
> +    console.log(node.children[0].children[0]);
Ok, can do.

2024-04-12 19:30 UTC, fakob commented on src/nodes/draw/draw.tsx
> +    drawingFunction.hash = () => newHash;
Hmm, actually that ended up in an error inside DRAW_Get_Bounds.getDrawingBounds
> TypeError: Cannot read properties of undefined (reading '×')
As I only need to set a unique value once. I kept it.

2024-04-12 19:44 UTC, fakob commented on cypress/e2e/pnp/parallelizable/testCombineObjects.cy.ts
> +    cy.wait(100);
So it seems that I do need a short wait after every`executeNodeByID` call.

2024-04-12 21:54 UTC, merged