Math node
fakob/plug-and-play pull request #69
Opened 2022-02-21 21:44 UTC by fakob

Added some math related nodes:
* A node which includes all operators and functions of Math. The display name changes according to the selected option
* Separate nodes for add, subtract, multiply and divide

I also added
* a number output widget and a conversion to number
* and allowed changing the type on the output
This way you can potentially do conversion, for example get a number out of the Label

<img width="1680" alt="Screen Shot 2022-02-21 at 22 43 36" src="https://user-images.githubusercontent.com/4619772/155029639-ad22d8a0-a6c5-4e11-8e0a-017804a70048.png">

2022-02-22 17:54 UTC, fakob commented
Made an additional update: Moved renaming of node out of the execute function into an onOptionChange callback which I added to the enum type. This way we can listen to updates independently.

2022-02-24 19:15 UTC, magnificus requested changes
I like the new "math function" node a lot, but there are some code issues here we need to fix (copy pasting)

2022-02-24 19:15 UTC, magnificus commented on src/nodes/datatypes/numberType.tsx
> +    if (typeof props.data !== 'number') {
I would use the sanitization step to fix this rather than checking data manually, but i can do that.

2022-02-24 19:15 UTC, magnificus commented on src/nodes/math.ts
> +    this.addInput('Input', new NumberType(false, -10, 10), 0, true);
could we add these via getDefaultIO function? it is cleaner than adding them in constructor

2022-02-24 19:15 UTC, magnificus commented on src/nodes/math.ts
> +export class MathFunction extends PPNode {
should definitely be pure node

2022-02-24 19:15 UTC, magnificus commented on src/nodes/math.ts
> +export class Multiply extends PPNode {
these nodes have way to much copy pasted code, they should be oneliners, make a node that is called "MathTwoElementOperation" or something with this logic that you are overriding, you should be able to make every node something like 1 single line.

2022-02-24 19:21 UTC, magnificus commented on src/nodes/math.ts
> +export class Multiply extends PPNode {
Tell me if you want me to checkout the branch and change this if you dont know what i am talking about

2022-02-24 20:45 UTC, fakob commented on src/nodes/math.ts
> +export class MathFunction extends PPNode {
Done, still not sure what a PureNode is though :-) One without side effects?

2022-02-24 20:47 UTC, fakob commented on src/nodes/math.ts
> +export class Multiply extends PPNode {
Please have a jab at it.

2022-02-24 21:16 UTC, magnificus commented on src/nodes/math.ts
> +export class MathFunction extends PPNode {
Yes, one where you say "if there is no difference in the result i generated in the function, then i dont need to tell any other nodes that i have run at all, im guaranteeing i dont have side effects"

2022-02-24 21:16 UTC, magnificus commented on src/nodes/math.ts
> +export class Multiply extends PPNode {
OK

2022-02-24 21:59 UTC, merged