Save presets
fakob/plug-and-play pull request #79
Opened 2022-03-18 19:47 UTC by fakob

For getting save presets to work I have added a couple of nodes and made some other changes:
* introduced a TriggerNode class - interestingly enough does the socket sometimes be added on the top, sometimes after all native sockets. not sure why
* changed some of the nodes to inherit from the TriggerNode class
* added Keyboard node - gets keyboard events
* added TriggerOnUpFlank node - create trigger on value change from 0 to 1
* added PassThrough node - pass input to output on trigger
* added If_Else node
* added Compare node - comparing 2 values
* added Check node - checking if an input is undefined or null
* updated Console node to also print the node id
* updated the Multiplier node to expose onPointerDown

Here the current save presets graph to test with:
[preset test 05 - 2022-03-18 at 20.32.23.ppgraph.zip](https://github.com/fakob/plug-and-play/files/8307231/preset.test.05.-.2022-03-18.at.20.32.23.ppgraph.zip)

![Screen_Shot_2022-03-16_at_19 55 31](https://user-images.githubusercontent.com/4619772/159073695-15b1c40f-cf39-49e6-9ca9-dd036fd0b3eb.png)

2022-03-19 09:04 UTC, magnificus requested changes
Looks very cool overall, just some minor things that we probably want to address

2022-03-19 09:04 UTC, magnificus commented on src/nodes/base.ts
> +export class Check extends PPNode {
Maybe name it something like IsValid?

2022-03-19 09:04 UTC, magnificus commented on src/utils/utils.ts
> +export const isInputTrue = (input: unknown): boolean => {
use this instead:

https://www.geeksforgeeks.org/lodash-_-truthy-method/

2022-03-19 09:04 UTC, magnificus commented on src/nodes/base.ts
> +    this.outputSocketArray[0].links.forEach((link) => {
same as above, this looks very sus, I think there are better ways to do the cascading here, lets talk about it?

2022-03-19 16:02 UTC, fakob commented on src/nodes/base.ts
> +export class PassThrough extends TriggerNode {
Not sure I understand what you mean with reroute-node, this one is as generic as it can get :-)
This node should pass data only when triggered instead of normal execution.

2022-03-19 16:04 UTC, fakob commented on src/nodes/base.ts
> +export class Check extends PPNode {
You are right. I think I want it to be more open to maybe also check for stuff like typeof, but maybe that should be a separate node then.

2022-03-19 16:11 UTC, fakob commented on src/utils/utils.ts
> +export const isInputTrue = (input: unknown): boolean => {
I can do that, but I would have to install lodash-contrib extra for this.

2022-03-19 16:21 UTC, fakob commented on src/nodes/base.ts
> +      if ((link.target.parent as any).triggerUpdate) {
We had a `trigger` function from before which get's called when using a triggerType button. This executes a local trigger function which could be used to execute something locally.
In addition I have introduced the `triggerUpdate` function which is the one present on all TriggerNodes. 
I guess they have different responsibilities now. So this does not make sense anymore. 
I probably need to make the triggerType to only trigger local functions unrelated to execution. Let's discuss this.

2022-03-20 10:38 UTC, magnificus commented on src/nodes/base.ts
> +      if ((link.target.parent as any).triggerUpdate) {
(y)

2022-03-20 10:39 UTC, magnificus commented on src/nodes/base.ts
> +export class PassThrough extends TriggerNode {
aha ok didnt understand it properly

2022-03-20 10:43 UTC, magnificus commented on src/utils/utils.ts
> +export const isInputTrue = (input: unknown): boolean => {
Yes, I think its worthwhile, as this will be used to parse user input, and they could do a lot of things that are hard to imagine (so library hopefully will have thought more about possibilities)

2022-03-24 17:44 UTC, magnificus approved these changes

2022-06-30 20:47 UTC, closed without merging