New trigger input
fakob/plug-and-play pull request #99
Opened 2022-04-21 20:27 UTC by fakob

This PR is not done yet, just wanted to show where I am at.
So I think I did what you suggested, but the Socket method `set data(newData: any)` is not called on the Trigger 1 socket when I change the Constant In value. Will have a look on the weekend, where my onSetData method should be hooked into so it gets triggered.

<img width="702" alt="Screen Shot 2022-04-21 at 22 15 20" src="https://user-images.githubusercontent.com/4619772/164546548-6599be9c-d9da-4432-aa57-c0a1a7574e12.png">

2022-04-23 09:54 UTC, magnificus approved these changes
looks ait added one comment

2022-04-23 09:54 UTC, magnificus commented on src/classes/SocketClass.ts
> +  get previousData(): any {
avoid copy pasting by merging this and getData

2022-04-25 20:04 UTC, fakob commented
Please have another look. 
I had to restrict to one trigger per node, as I did not get multiple triggers on one node to work properly.
With this task I saw my limitations in this area :-(  I think it works okayish now, but it is far from perfect.

2022-04-25 20:11 UTC, magnificus requested changes
Sorry but I'm a bit concerned about the execution flow now, if you want to feel free to merge, but we need to clean it up a bit

2022-04-25 20:11 UTC, magnificus commented on src/classes/NodeClass.ts
> +      if (!this.hasLinkedManualTrigger() || this.shouldNodeExecute()) {
we are unfortunately losing the desired encapsulation with this, as now the base node knows about the trigger type and it is affecting the workflow. Also I am concerned about performance here as we force a check of every socket (and print it all too) for every execution.

2022-05-15 20:35 UTC, merged